### ISSUE TITLE
New feature request: supporting complex numbers

### ISSUE THREAD

**Issue by dalin27** [microsoft/folx#13]
The code is working nicely for functions with real output (currently float32). It would be great if functions with complex outputs were supported as well.

**Comment by n-gao** [comment]
Hi David, I have heard this from other places as well and it would be great to add this feature! As I'm short on time at the moment, would you be interested in taking a look into how this could be incorporated best?

**Comment by n-gao** [comment]
Hi @dalin27, please confirm that #19 and #18 added proper support for complex functions for your use cases. If not it would be great if you could share more information!

**Comment by dalin27** [comment]
Yes it works great, thanks for the new implementation!
