### ISSUE TITLE
There is a error when I want to import folx

### ISSUE THREAD

**Issue by FXTY** [microsoft/folx#24]
When I want to import folx, there is a error shows 
'''python
File "/home/hanchenglei/software/miniconda3/envs/ferminet_jax_cp310/lib/python3.10/site-packages/folx/jvp.py", line 101
    idx = np.transpose(idx, new_order)[..., *(0,) * len(repeated_dims)]
                                            ^
SyntaxError: invalid syntax
'''
My environment is Python3.10.14, and numpy is 2.1.0.

**Comment by n-gao** [comment]
Thanks a lot for the bug report! Could you try Python 3.11? I haven't tested older versions and should probably bump the minimum version.

**Comment by FXTY** [comment]
Thanks for your reply. I just tried it and Python 3.11 did not faces this error.

**Comment by n-gao** [comment]
If there's no good reason to support 3.10, I would just increase the minimum python version to 3.11 and close this one. Is that fine with you?

**Comment by FXTY** [comment]
I am fine. Thanks!
